# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

source 'https://rubygems.org'

gem "rails", "~> 4.2.0"
gem "sass-rails", "~> 5.0.1"
gem "virtus", "~> 1.0.4"
gem "js-routes", "~> 1.0"
gem "tilt", "~> 1.4.1"
gem "fast_gettext", ">= 0.9.2"
gem "gettext_i18n_rails_js", "~> 1.0"
gem "gettext_i18n_rails", "~> 1.2"
gem "thin", "~> 1.7.2"

gem "haml-rails", ">= 0.8.2"
gem "kramdown", ">= 1.3.3"

group :development do
  gem "web-console", "~> 2.1", require: false
  gem "spring", ">= 1.3"
  gem "ruby_parser", "~> 3.6"
  gem "gettext", "~> 3.1", require: false
end

group :test do
  if ENV["RAILS_ENV"] == "test"
    source "https://rubygems.org"

    gem "rubocop"
    gem "rake"
    gem "brakeman"

    gem "rspec-rails", "~> 3.4.2"
    gem "capybara", "~> 2.7.1"
    gem "guard-rspec", "~> 4.7.2"
  end
end

instance_eval(File.read("Gemfile.local")) if File.exist? "Gemfile.local"
